# Generated by Django 5.1.7 on 2025-03-19 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_type_album_album_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
