# Generated by Django 5.1.7 on 2025-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_delete_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='total_tracks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
