# Generated by Django 5.1.7 on 2025-03-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_total_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('ep', 'Ep'), ('album', 'Album')], default='single', null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='total_tracks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
