# Generated by Django 5.1.7 on 2025-03-11 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85180254-9d5d-4dff-8cb9-529608850133'), primary_key=True, serialize=False, unique=True),
        ),
    ]
