# Generated by Django 5.1.7 on 2025-03-14 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_deleted_at_remove_customuser_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d520a40c-7f07-4d15-b5e7-b3c606a6ab61'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d520a40c-7f07-4d15-b5e7-b3c606a6ab61'), primary_key=True, serialize=False, unique=True),
        ),
    ]
