# Generated by Django 5.1.7 on 2025-03-14 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_is_staff_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('artist_manager', 'Artist Manager'), ('artist', 'Artist')], default='artist'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('476ccdb0-5568-4897-bdc0-0966b1497d41'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
