# Generated by Django 5.1.7 on 2025-03-14 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_is_active_customuser_is_removed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e343af11-8b92-4148-a25a-52c6a771108e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
