# Generated by Django 5.1.7 on 2025-03-14 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f50a98c-21c6-404a-b049-9f98d5017e56'), primary_key=True, serialize=False, unique=True),
        ),
    ]
