# Generated by Django 5.1.7 on 2025-03-14 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c492f7b-74ef-4cf5-90c1-91814337930f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
