# Generated by Django 5.1.7 on 2025-03-14 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a86b899-9883-4042-ac5a-d35d9a3bceb5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
