# Generated by Django 5.1.7 on 2025-03-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, verbose_name='last name'),
        ),
    ]
