# Generated by Django 5.1.7 on 2025-03-14 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d520a40c-7f07-4d15-b5e7-b3c606a6ab61'), primary_key=True, serialize=False, unique=True),
        ),
    ]
