# Generated by Django 5.1.7 on 2025-03-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
