# Generated by Django 5.1.7 on 2025-03-14 06:12

import core.base.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0003_delete_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8f50a98c-21c6-404a-b049-9f98d5017e56'), primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(unique=True, verbose_name='artist name')),
                ('first_release_year', models.IntegerField(blank=True)),
                ('no_of_albums_released', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Artist Profile',
            },
            bases=(models.Model, core.base.models.Profile),
        ),
    ]
