# Generated by Django 5.1.7 on 2025-03-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_first_release_year_alter_artist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='artist name'),
        ),
    ]
