# Generated by Django 5.1.7 on 2025-03-14 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c492f7b-74ef-4cf5-90c1-91814337930f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
    ]
