# Generated by Django 5.1.7 on 2025-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0006_alter_artist_manager_alter_artist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="artists/cover"),
        ),
        migrations.AddField(
            model_name="artist",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="artists/profile"),
        ),
    ]
