# Generated by Django 5.1.7 on 2025-03-19 03:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("albums", "0003_delete_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("rnb", "Rnb"),
                            ("country", "Country"),
                            ("classic", "Classic"),
                            ("rock", "Rock"),
                            ("jazz", "Jazz"),
                        ]
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song",
                        to="albums.album",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
