# Generated by Django 5.1.7 on 2025-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rnb', 'Rnb'), ('country', 'Country'), ('classic', 'Classic'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('indie', 'Indie'), ('jpop', 'Jpop')]),
        ),
    ]
